// Code generated by protoc-gen-go. DO NOT EDIT.
// source: microx/srv/passport/api/passport.proto

package go_micro_srv_passport

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiredAt            int64    `protobuf:"varint,4,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenInfo) Reset()         { *m = TokenInfo{} }
func (m *TokenInfo) String() string { return proto.CompactTextString(m) }
func (*TokenInfo) ProtoMessage()    {}
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{0}
}

func (m *TokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenInfo.Unmarshal(m, b)
}
func (m *TokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenInfo.Marshal(b, m, deterministic)
}
func (m *TokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenInfo.Merge(m, src)
}
func (m *TokenInfo) XXX_Size() int {
	return xxx_messageInfo_TokenInfo.Size(m)
}
func (m *TokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TokenInfo proto.InternalMessageInfo

func (m *TokenInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TokenInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenInfo) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *TokenInfo) GetExpiredAt() int64 {
	if m != nil {
		return m.ExpiredAt
	}
	return 0
}

type Request struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SmsLoginRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsLoginRequest) Reset()         { *m = SmsLoginRequest{} }
func (m *SmsLoginRequest) String() string { return proto.CompactTextString(m) }
func (*SmsLoginRequest) ProtoMessage()    {}
func (*SmsLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{3}
}

func (m *SmsLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsLoginRequest.Unmarshal(m, b)
}
func (m *SmsLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsLoginRequest.Marshal(b, m, deterministic)
}
func (m *SmsLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsLoginRequest.Merge(m, src)
}
func (m *SmsLoginRequest) XXX_Size() int {
	return xxx_messageInfo_SmsLoginRequest.Size(m)
}
func (m *SmsLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsLoginRequest proto.InternalMessageInfo

func (m *SmsLoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SmsLoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SmsLoginResponse struct {
	TokenInfo            *TokenInfo `protobuf:"bytes,1,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SmsLoginResponse) Reset()         { *m = SmsLoginResponse{} }
func (m *SmsLoginResponse) String() string { return proto.CompactTextString(m) }
func (*SmsLoginResponse) ProtoMessage()    {}
func (*SmsLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{4}
}

func (m *SmsLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsLoginResponse.Unmarshal(m, b)
}
func (m *SmsLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsLoginResponse.Marshal(b, m, deterministic)
}
func (m *SmsLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsLoginResponse.Merge(m, src)
}
func (m *SmsLoginResponse) XXX_Size() int {
	return xxx_messageInfo_SmsLoginResponse.Size(m)
}
func (m *SmsLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmsLoginResponse proto.InternalMessageInfo

func (m *SmsLoginResponse) GetTokenInfo() *TokenInfo {
	if m != nil {
		return m.TokenInfo
	}
	return nil
}

type LoginRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{5}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type LoginResponse struct {
	TokenInfo            *TokenInfo `protobuf:"bytes,1,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{6}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetTokenInfo() *TokenInfo {
	if m != nil {
		return m.TokenInfo
	}
	return nil
}

type OAuthLoginRequest struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuthLoginRequest) Reset()         { *m = OAuthLoginRequest{} }
func (m *OAuthLoginRequest) String() string { return proto.CompactTextString(m) }
func (*OAuthLoginRequest) ProtoMessage()    {}
func (*OAuthLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{7}
}

func (m *OAuthLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthLoginRequest.Unmarshal(m, b)
}
func (m *OAuthLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthLoginRequest.Marshal(b, m, deterministic)
}
func (m *OAuthLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthLoginRequest.Merge(m, src)
}
func (m *OAuthLoginRequest) XXX_Size() int {
	return xxx_messageInfo_OAuthLoginRequest.Size(m)
}
func (m *OAuthLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthLoginRequest proto.InternalMessageInfo

func (m *OAuthLoginRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *OAuthLoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type OAuthLoginResponse struct {
	TokenInfo            *TokenInfo `protobuf:"bytes,1,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OAuthLoginResponse) Reset()         { *m = OAuthLoginResponse{} }
func (m *OAuthLoginResponse) String() string { return proto.CompactTextString(m) }
func (*OAuthLoginResponse) ProtoMessage()    {}
func (*OAuthLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{8}
}

func (m *OAuthLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthLoginResponse.Unmarshal(m, b)
}
func (m *OAuthLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthLoginResponse.Marshal(b, m, deterministic)
}
func (m *OAuthLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthLoginResponse.Merge(m, src)
}
func (m *OAuthLoginResponse) XXX_Size() int {
	return xxx_messageInfo_OAuthLoginResponse.Size(m)
}
func (m *OAuthLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthLoginResponse proto.InternalMessageInfo

func (m *OAuthLoginResponse) GetTokenInfo() *TokenInfo {
	if m != nil {
		return m.TokenInfo
	}
	return nil
}

type TokenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{9}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

type TokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{10}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

type SetPwdRequest struct {
	Passwd               string   `protobuf:"bytes,1,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPwdRequest) Reset()         { *m = SetPwdRequest{} }
func (m *SetPwdRequest) String() string { return proto.CompactTextString(m) }
func (*SetPwdRequest) ProtoMessage()    {}
func (*SetPwdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{11}
}

func (m *SetPwdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPwdRequest.Unmarshal(m, b)
}
func (m *SetPwdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPwdRequest.Marshal(b, m, deterministic)
}
func (m *SetPwdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPwdRequest.Merge(m, src)
}
func (m *SetPwdRequest) XXX_Size() int {
	return xxx_messageInfo_SetPwdRequest.Size(m)
}
func (m *SetPwdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPwdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPwdRequest proto.InternalMessageInfo

func (m *SetPwdRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type SetPwdResponse struct {
	TokenInfo            *TokenInfo `protobuf:"bytes,1,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetPwdResponse) Reset()         { *m = SetPwdResponse{} }
func (m *SetPwdResponse) String() string { return proto.CompactTextString(m) }
func (*SetPwdResponse) ProtoMessage()    {}
func (*SetPwdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f06548ff1d7c423b, []int{12}
}

func (m *SetPwdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPwdResponse.Unmarshal(m, b)
}
func (m *SetPwdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPwdResponse.Marshal(b, m, deterministic)
}
func (m *SetPwdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPwdResponse.Merge(m, src)
}
func (m *SetPwdResponse) XXX_Size() int {
	return xxx_messageInfo_SetPwdResponse.Size(m)
}
func (m *SetPwdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPwdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPwdResponse proto.InternalMessageInfo

func (m *SetPwdResponse) GetTokenInfo() *TokenInfo {
	if m != nil {
		return m.TokenInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*TokenInfo)(nil), "go.micro.srv.passport.TokenInfo")
	proto.RegisterType((*Request)(nil), "go.micro.srv.passport.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.passport.Response")
	proto.RegisterType((*SmsLoginRequest)(nil), "go.micro.srv.passport.SmsLoginRequest")
	proto.RegisterType((*SmsLoginResponse)(nil), "go.micro.srv.passport.SmsLoginResponse")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.srv.passport.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.srv.passport.LoginResponse")
	proto.RegisterType((*OAuthLoginRequest)(nil), "go.micro.srv.passport.OAuthLoginRequest")
	proto.RegisterType((*OAuthLoginResponse)(nil), "go.micro.srv.passport.OAuthLoginResponse")
	proto.RegisterType((*TokenRequest)(nil), "go.micro.srv.passport.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "go.micro.srv.passport.TokenResponse")
	proto.RegisterType((*SetPwdRequest)(nil), "go.micro.srv.passport.SetPwdRequest")
	proto.RegisterType((*SetPwdResponse)(nil), "go.micro.srv.passport.SetPwdResponse")
}

func init() {
	proto.RegisterFile("microx/srv/passport/api/passport.proto", fileDescriptor_f06548ff1d7c423b)
}

var fileDescriptor_f06548ff1d7c423b = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x5e, 0xd7, 0x2e, 0x6b, 0x3e, 0x9a, 0x0d, 0x2c, 0x18, 0x55, 0x24, 0x46, 0x49, 0x61, 0x2b,
	0x97, 0x54, 0x1a, 0x67, 0x40, 0x13, 0x17, 0x26, 0x21, 0x51, 0xd2, 0x01, 0x17, 0x50, 0x95, 0x35,
	0xee, 0x66, 0xd1, 0xc4, 0xc1, 0x76, 0xb7, 0x9d, 0xf8, 0x37, 0xfc, 0x4f, 0x54, 0xc7, 0xc9, 0x1a,
	0xb6, 0xac, 0x3d, 0xf4, 0xe6, 0xcf, 0xef, 0x7b, 0xdf, 0xfb, 0xde, 0xf3, 0x93, 0x71, 0x10, 0xb3,
	0xb1, 0xe0, 0xd7, 0x7d, 0x29, 0x2e, 0xfb, 0x69, 0x28, 0x65, 0xca, 0x85, 0xea, 0x87, 0x29, 0x2b,
	0x80, 0x9f, 0x0a, 0xae, 0x38, 0x79, 0x72, 0xce, 0x7d, 0x4d, 0xf5, 0xa5, 0xb8, 0xf4, 0xf3, 0xa0,
	0xf7, 0x07, 0xf6, 0x29, 0xff, 0x45, 0x93, 0x93, 0x64, 0xc2, 0xc9, 0x53, 0x6c, 0xcf, 0x24, 0x15,
	0x23, 0x16, 0xb5, 0x6b, 0x9d, 0x5a, 0xaf, 0x1e, 0x58, 0x73, 0x78, 0x12, 0x91, 0xc7, 0xd8, 0x52,
	0x73, 0x56, 0x7b, 0xb3, 0x53, 0xeb, 0xd9, 0x41, 0x06, 0x48, 0x17, 0x8e, 0xa0, 0x13, 0x41, 0xe5,
	0xc5, 0x28, 0x8b, 0xd6, 0x75, 0xb4, 0x65, 0x2e, 0xb5, 0x2e, 0x79, 0x06, 0xd0, 0xeb, 0x94, 0x09,
	0x1a, 0x8d, 0x42, 0xd5, 0x6e, 0x68, 0x59, 0xdb, 0xdc, 0x1c, 0x2b, 0xef, 0x05, 0xb6, 0x03, 0xfa,
	0x7b, 0x46, 0xa5, 0x22, 0x7b, 0xb0, 0x62, 0x7e, 0xc6, 0xa6, 0x54, 0x17, 0xb7, 0x03, 0x83, 0xbc,
	0x7d, 0x34, 0x03, 0x2a, 0x53, 0x9e, 0x48, 0x4a, 0x08, 0x1a, 0x63, 0x1e, 0xe5, 0x0c, 0x7d, 0xf6,
	0xde, 0x62, 0x77, 0x18, 0xcb, 0x4f, 0xfc, 0x9c, 0x25, 0x4b, 0xa4, 0x8a, 0xf4, 0xcd, 0x85, 0xf4,
	0x21, 0x1e, 0xde, 0xa4, 0x9b, 0x32, 0xef, 0x01, 0xdd, 0xd1, 0x88, 0x25, 0x13, 0xae, 0x35, 0x1e,
	0x1c, 0x75, 0xfc, 0x3b, 0x27, 0xe8, 0x17, 0xe3, 0x0b, 0x6c, 0x95, 0x1f, 0xbd, 0x77, 0x68, 0xad,
	0x64, 0x68, 0x0f, 0xd6, 0x5c, 0xe8, 0x2a, 0x32, 0x96, 0x0c, 0xf2, 0x06, 0x70, 0xd6, 0xec, 0xe8,
	0x03, 0x1e, 0x7d, 0x3e, 0x9e, 0xa9, 0x8b, 0x92, 0x2d, 0x17, 0xcd, 0x74, 0x1a, 0xaa, 0x09, 0x17,
	0xb1, 0x31, 0x56, 0xe0, 0x3b, 0x67, 0xf5, 0x15, 0x64, 0x51, 0x64, 0x5d, 0xde, 0x76, 0xd0, 0xd2,
	0xf7, 0xc6, 0x96, 0xb7, 0x0b, 0xc7, 0xe0, 0xac, 0x82, 0x77, 0x08, 0x67, 0x48, 0xd5, 0xe0, 0x2a,
	0x5a, 0x98, 0xa7, 0x99, 0x5b, 0xad, 0x34, 0xb7, 0x2f, 0xd8, 0xc9, 0x89, 0x6b, 0x32, 0x77, 0xf4,
	0xb7, 0x81, 0xe6, 0xc0, 0x30, 0xc8, 0x47, 0xd4, 0x87, 0xb1, 0x24, 0xfb, 0x15, 0x02, 0xc6, 0x9e,
	0xfb, 0xbc, 0x32, 0x6e, 0x1a, 0xda, 0x20, 0x3f, 0xd1, 0xcc, 0xd7, 0x8e, 0x1c, 0x54, 0xd0, 0xff,
	0x5b, 0x6b, 0xf7, 0x70, 0x29, 0xaf, 0x90, 0x3f, 0xc5, 0x56, 0xa6, 0xdd, 0xad, 0xc8, 0x29, 0x09,
	0xbf, 0xbc, 0x9f, 0x54, 0xa8, 0x8e, 0x81, 0x9b, 0xf7, 0x27, 0xbd, 0x8a, 0xac, 0x5b, 0x7b, 0xe6,
	0xbe, 0x5e, 0x81, 0x59, 0x14, 0xf9, 0x01, 0xe7, 0x5b, 0x38, 0x65, 0x51, 0xa8, 0x68, 0xf6, 0x85,
	0x74, 0xef, 0x7b, 0xae, 0x65, 0x2d, 0x94, 0x17, 0x69, 0x83, 0x7c, 0x87, 0x95, 0x6d, 0x08, 0xa9,
	0xca, 0x28, 0x6d, 0x9a, 0xfb, 0x6a, 0x09, 0x2b, 0x17, 0x3e, 0xb3, 0xf4, 0x3f, 0xfb, 0xe6, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x10, 0x83, 0x42, 0x91, 0x05, 0x00, 0x00,
}
