// Code generated by protoc-gen-go. DO NOT EDIT.
// source: microx/srv/gid/api/gid.proto

package go_micro_srv_gid

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b31248ccc5c0153, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b31248ccc5c0153, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MultiRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiRequest) Reset()         { *m = MultiRequest{} }
func (m *MultiRequest) String() string { return proto.CompactTextString(m) }
func (*MultiRequest) ProtoMessage()    {}
func (*MultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b31248ccc5c0153, []int{2}
}

func (m *MultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiRequest.Unmarshal(m, b)
}
func (m *MultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiRequest.Marshal(b, m, deterministic)
}
func (m *MultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiRequest.Merge(m, src)
}
func (m *MultiRequest) XXX_Size() int {
	return xxx_messageInfo_MultiRequest.Size(m)
}
func (m *MultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiRequest proto.InternalMessageInfo

func (m *MultiRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type MultiResponse struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiResponse) Reset()         { *m = MultiResponse{} }
func (m *MultiResponse) String() string { return proto.CompactTextString(m) }
func (*MultiResponse) ProtoMessage()    {}
func (*MultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b31248ccc5c0153, []int{3}
}

func (m *MultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiResponse.Unmarshal(m, b)
}
func (m *MultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiResponse.Marshal(b, m, deterministic)
}
func (m *MultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiResponse.Merge(m, src)
}
func (m *MultiResponse) XXX_Size() int {
	return xxx_messageInfo_MultiResponse.Size(m)
}
func (m *MultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiResponse proto.InternalMessageInfo

func (m *MultiResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.gid.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.gid.Response")
	proto.RegisterType((*MultiRequest)(nil), "go.micro.srv.gid.MultiRequest")
	proto.RegisterType((*MultiResponse)(nil), "go.micro.srv.gid.MultiResponse")
}

func init() { proto.RegisterFile("microx/srv/gid/api/gid.proto", fileDescriptor_9b31248ccc5c0153) }

var fileDescriptor_9b31248ccc5c0153 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0xcd, 0x4c, 0x2e,
	0xca, 0xaf, 0xd0, 0x2f, 0x2e, 0x2a, 0xd3, 0x4f, 0xcf, 0x4c, 0xd1, 0x4f, 0x2c, 0xc8, 0x04, 0xd1,
	0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x02, 0xe9, 0xf9, 0x7a, 0x60, 0x05, 0x7a, 0xc5, 0x45,
	0x65, 0x7a, 0xe9, 0x99, 0x29, 0x4a, 0x9c, 0x5c, 0xec, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x4a, 0x52, 0x5c, 0x1c, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x7c, 0x5c, 0x4c,
	0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x4c, 0x99, 0x29, 0x4a, 0x2a, 0x5c, 0x3c,
	0xbe, 0xa5, 0x39, 0x25, 0x99, 0x50, 0xb5, 0x42, 0x22, 0x5c, 0xac, 0xc9, 0xf9, 0xa5, 0x79, 0x25,
	0x60, 0x25, 0xac, 0x41, 0x10, 0x8e, 0x92, 0x22, 0x17, 0x2f, 0x54, 0x15, 0xd4, 0x18, 0x01, 0x2e,
	0xe6, 0xcc, 0x94, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0xe6, 0x20, 0x10, 0xd3, 0x68, 0x3a, 0x23,
	0x17, 0xb3, 0x7b, 0x66, 0x8a, 0x90, 0x23, 0x17, 0x9b, 0x7b, 0x6a, 0x89, 0x7f, 0x5e, 0xaa, 0x90,
	0xa4, 0x1e, 0xba, 0xa3, 0xf4, 0xa0, 0xb6, 0x48, 0x49, 0x61, 0x93, 0x82, 0x18, 0xad, 0xc4, 0x20,
	0xe4, 0xcb, 0xc5, 0xe1, 0x9e, 0x5a, 0x02, 0xb6, 0x50, 0x48, 0x0e, 0x53, 0x25, 0xb2, 0x7b, 0xa5,
	0xe4, 0x71, 0xca, 0xc3, 0x8c, 0x4b, 0x62, 0x03, 0x07, 0x91, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x99, 0x53, 0x59, 0x93, 0x42, 0x01, 0x00, 0x00,
}
